name: Linux CI runner for NCM6B

on:
  push:
    branches:
      - linux-5.10-gen-rkr3.4

jobs:
  build:
    permissions: write-all
    name: kernel ncm6b runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y gcc-9 openssl devscripts build-essential crossbuild-essential-arm64 bc bison
          sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libelf-dev libssl-dev kmod cpio libssl-dev

      - name: Clone and compile
        run: |
          mkdir out
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make rockchip_linux_defconfig
          make dtbs Image -j 16
          make modules -j 16
          sudo make modules_install INSTALL_MOD_PATH=out
 
      - name: Copy deb files and create archive
        run: |
          mkdir linux && mkdir -p dtb/rockchip && mkdir -p modules
          cp -fv arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtb dtb/rockchip
          cp -fv arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dtb dtb/rockchip
          cp -fv arch/arm64/boot/dts/rockchip/overlay/*rk3588*.dtbo dtb/rockchip
          cp -fv arch/arm64/boot/dts/rockchip/overlay/rock-5b*.dtbo dtb/rockchip
          cp -frv arch/arm64/boot/Image dtb linux
          tar -Jcf linux.tar.xz linux
          cp -frv out/lib/modules/* modules
          tar -Jcf modules.tar.xz modules

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v2024.02-6TOPS-rc1"
          body: |
            ## Linux Kernel 6TOPS rc1
            - Include 5B DT
          files: |
           linux.tar.xz
           modules.tar.xz
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
